pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = "192.168.64.3/test/frontend"
        DOCKER_TAG = "${env.BUILD_NUMBER}"
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build and Push Docker Image') {
            steps {
                script {
                    docker.build("${DOCKER_IMAGE}:${DOCKER_TAG}", "-f frontend/Dockerfile ./frontend")
                    docker.withRegistry('https://192.168.64.3', 'harbor-hyeongjun') {
                        docker.image("${DOCKER_IMAGE}:${DOCKER_TAG}").push()
                    }
                }
            }
        }
        
        stage('Deploy') {
            steps {
                sshagent(['ssh-web-server']) {
                    sh """
                        ssh hj@192.168.64.4 << EOF
                        docker pull ${DOCKER_IMAGE}:${DOCKER_TAG}
                        docker stop frontend || true
                        docker rm frontend || true
                        docker run -d --name frontend -p 80:80 ${DOCKER_IMAGE}:${DOCKER_TAG}
                        EOF
                    """
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}